### ISSUE TITLE
Design simulation vignette matters

### ISSUE THREAD

**Issue by erex** [distanceexamples/book-dsims#1]
- Think the reference to the 2015 book section is inaccurate.  Probably want 2.5.2 rather than 3.5.2 and I don't see reference to simulation in 11.1.1.
- ![image](https://user-images.githubusercontent.com/330744/192095988-5e1a8a49-df82-4a6f-8b94-24241bfbbdd5.png)
- simulation could be perceived as skewed in favour of the randomised designs because the effort differs between subjective and random designs.  
- ![image](https://user-images.githubusercontent.com/330744/192096129-ca683753-dc24-47cc-8e45-bd092fd74689.png)
- Could be more convincing if randomised designs are created to mimic effort more similar to the 340km in the subjective design

**Comment by LHMarshall** [comment]
I have changed the references to the book and added a Discussion section. The subjectvie design was not created for comparison with the randomised designs only as an example of what not to do. Making the effort comparable doesn't make the designs comparable in cost. For the randomised designs they were designed to be comparable (they have similar cyclic trackline lengths - although this only holds if on-effort and off-effort transit is the same cost). The cyclic trackline length of the subjective design is not easily determined and the cost of the transects are different any way as presumably easier to walk the paths and that is why a design like this would be attempted (or not now hopefully!).  I hope I have now highlighted these aims clearly in the discussion.
